name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "tsconfig.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.ts"
      - "tsconfig.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci.yml"

jobs:
  ci:
    strategy:
      matrix:
        node: [18.x, 20.x, 21.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run CI
        run: pnpm run ci
