name: Playwright Tests
on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "**.tsx"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/playwright.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.ts"
      - "**.tsx"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/playwright.yml"
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build package
      - run: pnpm build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test
